// Continut initial pentru CMS (Ghid / FAQ / Cookies) — TRILINGV, in backend
// ca sa functioneze si in Docker (unde frontend/src nu exista).
// Dupa seed, totul se gestioneaza din Admin → Continut.
const GUIDE_ICONS = ['⏳', '🥕', '🥄', '🤗', '📅', '👀', '🍎', '🔢', '🥣', '⚖️', '🍼', '🕒', '⚠️', '🚫', '🛡️', '😟', '🚫', '🧂', '💧', '🆘'];

const GUIDE = [
  { q: ['Când încep diversificarea?', 'Когда начинать прикорм?', 'When to start solids?'], a: ['În jur de 6 luni: bebe ține bine capul, stă cu sprijin și arată interes pentru mâncare. Pediatrul confirmă momentul potrivit.', 'Около 6 месяцев: малыш уверенно держит голову, сидит с поддержкой и интересуется едой. Точный момент подтвердит педиатр.', 'Around 6 months: baby holds the head steady, sits with support and shows interest in food. Your pediatrician confirms the right moment.'] },
  { q: ['Cu ce încep diversificarea?', 'С чего начать?', 'What to start with?'], a: ['Legume simple (morcov, dovlecel, cartof dulce), câte un aliment nou la 2–3 zile, cu texturi fine la început.', 'Простые овощи (морковь, кабачок, батат), по одному новому продукту каждые 2–3 дня, с нежной текстурой.', 'Simple veggies (carrot, zucchini, sweet potato), one new food every 2–3 days, with smooth textures at first.'] },
  { q: ['Cât trebuie să mănânce?', 'Сколько должен съедать?', 'How much should they eat?'], a: ['La început câteva lingurițe pe zi sunt suficiente; laptele rămâne alimentul de bază până la 1 an. Mărește porțiile treptat, după apetit.', 'Вначале достаточно нескольких ложечек в день; молоко остаётся основой питания до года. Увеличивайте порции постепенно, по аппетиту.', 'A few teaspoons a day is plenty at first; milk stays the main food until age one. Grow portions gradually, following appetite.'] },
  { q: ['Ce fac dacă refuză mâncarea?', 'Что делать, если отказывается?', 'What if baby refuses?'], a: ['E normal. Propune din nou peste câteva zile, fără forțare — acceptarea vine de obicei după 8–10 expuneri.', 'Это нормально. Предложите снова через несколько дней, без принуждения — принятие обычно приходит после 8–10 попыток.', "That's normal. Offer again in a few days without pressure — acceptance usually comes after 8–10 exposures."] },
  { q: ['Când este recomandat să încep diversificarea?', 'Когда рекомендуют начинать прикорм?', 'When is starting solids recommended?'], a: ['În general, diversificarea începe în jurul vârstei de 6 luni, atunci când bebelușul este pregătit din punct de vedere al dezvoltării.', 'Обычно прикорм начинают около 6 месяцев, когда малыш готов к нему по развитию.', 'Generally around 6 months, when your baby is developmentally ready.'] },
  { q: ['Cum îmi dau seama că bebelușul este pregătit?', 'Как понять, что малыш готов?', 'How do I know my baby is ready?'], a: ['Printre semne se numără capacitatea de a sta cu sprijin, controlul bun al capului și gâtului și interesul pentru alimente.', 'Признаки готовности: умение сидеть с поддержкой, хороший контроль головы и шеи, интерес к еде.', 'Readiness signs include sitting with support, good head and neck control, and interest in foods.'] },
  { q: ['Cu ce alimente este bine să încep?', 'Какие продукты подойдут первыми?', 'Which first foods are best?'], a: ['Poți începe cu alimente simple și potrivite vârstei: legume, fructe, cereale, carne, ou și alte alimente nutritive, introduse treptat.', 'Простые продукты по возрасту: овощи, фрукты, каши, мясо, яйцо и другие питательные продукты — вводите постепенно.', 'Start with simple, age-appropriate foods: veggies, fruits, cereals, meat, egg and other nutritious foods, introduced gradually.'] },
  { q: ['Câte alimente noi pot introduce odată?', 'Сколько новых продуктов вводить сразу?', 'How many new foods at once?'], a: ['La început este util să introduci alimentele noi treptat, ca să observi mai ușor eventualele reacții.', 'Вначале вводите новые продукты постепенно, чтобы легче заметить возможные реакции.', 'At first, introduce new foods gradually so you can spot any reactions more easily.'] },
  { q: ['Trebuie să încep cu piureuri?', 'Обязательно начинать с пюре?', 'Must I start with purees?'], a: ['Nu neapărat. Textura se adaptează vârstei și abilităților: alimente pasate, dar și texturi moi pentru explorare autonomă.', 'Нет. Текстуру подбирайте по возрасту и навыкам: пюре, а также мягкие кусочки для самостоятельного изучения.', 'Not necessarily. Match texture to age and skills: purees, but also soft textures for self-feeding exploration.'] },
  { q: ['Cât de mult trebuie să mănânce la început?', 'Сколько должен съедать вначале?', 'How much should baby eat at first?'], a: ['Cantitatea variază mult. La început scopul este familiarizarea cu gusturile și texturile, nu o cantitate anume.', 'Количество сильно различается. Вначале главное — знакомство со вкусами и текстурами, а не объём.', 'Amounts vary a lot. Early on the goal is exploring tastes and textures, not a set quantity.'] },
  { q: ['Laptele rămâne important după diversificare?', 'Молоко остаётся важным после прикорма?', 'Does milk still matter after starting solids?'], a: ['Da. La începutul diversificării, laptele matern sau formula continuă să aibă un rol important în alimentație.', 'Да. В начале прикорма грудное молоко или смесь продолжают играть важную роль в питании.', 'Yes. Early in weaning, breast milk or formula keeps playing a major role in nutrition.'] },
  { q: ['Cât de des ofer alimente solide?', 'Как часто давать твёрдую пищу?', 'How often to offer solid food?'], a: ['Frecvența meselor crește treptat, în funcție de vârstă, dezvoltare și apetitul copilului.', 'Частота приёмов растёт постепенно — по возрасту, развитию и аппетиту ребёнка.', 'Meal frequency grows gradually with age, development and appetite.'] },
  { q: ['Pot introduce alergenii?', 'Можно ли вводить аллергены?', 'Can I introduce allergens?'], a: ['Alimentele alergene pot fi introduse în perioada diversificării, în forme potrivite vârstei și în siguranță. La factori de risc, discută cu pediatrul.', 'Аллергенные продукты можно вводить в период прикорма, в безопасной форме по возрасту. При факторах риска посоветуйтесь с педиатром.', 'Allergenic foods can be introduced during weaning in safe, age-appropriate forms. With risk factors, talk to your pediatrician.'] },
  { q: ['Ce alimente trebuie evitate la început?', 'Чего избегать вначале?', 'What to avoid at the start?'], a: ['Alimentele cu risc de înec sau nepotrivite sugarilor trebuie evitate; la fel, anumite alimente și băuturi în primul an de viață.', 'Избегайте продуктов с риском удушья и неподходящих младенцам; также отдельных продуктов и напитков на первом году жизни.', 'Avoid choking hazards and foods unsuitable for infants, plus certain foods and drinks in the first year.'] },
  { q: ['Cum previn riscul de înec?', 'Как предотвратить риск удушья?', 'How do I prevent choking?'], a: ['Bebelușul stă supravegheat permanent la masă, poziționat corect, și primește alimente cu formă și textură adecvate vârstei.', 'Малыш ест только под постоянным присмотром, в правильном положении, получая пищу подходящей формы и текстуры.', 'Baby eats only under constant supervision, seated correctly, with age-appropriate shapes and textures.'] },
  { q: ['E normal să refuze anumite alimente?', 'Нормально ли отказываться от еды?', 'Is food refusal normal?'], a: ['Da, refuzul e frecvent la început. Uneori sunt necesare mai multe expuneri până acceptă un gust sau o textură nouă.', 'Да, отказ вначале — частое явление. Иногда нужно несколько попыток, чтобы принять новый вкус или текстуру.', 'Yes, refusal is common at first. Several exposures are sometimes needed before a new taste or texture is accepted.'] },
  { q: ['Trebuie să forțez bebelușul să mănânce?', 'Нужно ли заставлять есть?', 'Should I force my baby to eat?'], a: ['Nu. Respectă semnalele de foame și sațietate ale copilului și evită forțarea alimentației.', 'Нет. Уважайте сигналы голода и сытости ребёнка и не заставляйте есть.', 'No. Respect hunger and fullness cues and avoid pressuring.'] },
  { q: ['Pot folosi sare și zahăr?', 'Можно ли соль и сахар?', 'Can I use salt and sugar?'], a: ['Nu este recomandat să obișnuiești bebelușul cu alimente bogate în sare sau zahăr. Alimentele simple lasă copilul să descopere gusturile naturale.', 'Не приучайте малыша к солёному и сладкому. Простые продукты помогают узнать натуральные вкусы.', "It's best not to get baby used to salty or sugary foods. Plain foods let them discover natural tastes."] },
  { q: ['Când pot introduce apa?', 'Когда можно давать воду?', 'When can I offer water?'], a: ['Odată cu alimentele solide, apa poate fi oferită în cantități potrivite, fără să înlocuiască laptele ca sursă principală în această etapă.', 'С началом прикорма воду можно предлагать в подходящих количествах, не заменяя ею молоко как основу питания.', 'With solids, water can be offered in suitable amounts without replacing milk as the main nutrition at this stage.'] },
  { q: ['Ce fac la o reacție după un aliment nou?', 'Что делать при реакции на новый продукт?', 'What if baby reacts to a new food?'], a: ['Oprește alimentul suspect și urmărește simptomele. La reacție severă (respirație dificilă, umflarea feței/buzelor, stare alterată) cere imediat ajutor medical.', 'Уберите подозрительный продукт и наблюдайте. При тяжёлой реакции (затруднённое дыхание, отёк лица/губ, ухудшение состояния) срочно вызывайте врача.', 'Stop the suspect food and watch symptoms. For severe reactions (trouble breathing, face/lip swelling, poor condition) seek emergency care.'] }
];

const COOKIES = [
  { h: ['1. Ce sunt cookie-urile și stocarea locală?', '1. Что такое cookie и локальное хранилище?', '1. What are cookies and local storage?'], p: ['Cookie-urile sunt fișiere text mici salvate de browser. Stocarea locală (localStorage) păstrează date direct în browserul tău. Ambele ne ajută să ținem minte preferințele tale între vizite.', 'Cookie — небольшие текстовые файлы браузера. Локальное хранилище (localStorage) хранит данные прямо в вашем браузере и помогает запоминать настройки между визитами.', 'Cookies are small text files saved by your browser. Local storage (localStorage) keeps data right in your browser and remembers your preferences between visits.'] },
  { h: ['2. Ce folosim pe GustBebe?', '2. Что использует GustBebe?', '2. What does GustBebe use?'], p: ['Strictul necesar: tokenul de autentificare (dacă te loghezi), limba aleasă a interfeței și alegerea ta privind acest banner. Nu folosim cookie-uri de urmărire, analiză sau publicitate.', 'Только необходимое: токен входа (если вы авторизованы), выбранный язык и ваш выбор по этому баннеру. Трекинга, аналитики и рекламы нет.', "Strictly what's needed: your login token (if you sign in), the interface language, and your banner choice. No tracking, analytics or advertising cookies."] },
  { h: ['3. Cât păstrăm datele?', '3. Сколько храним?', '3. How long is data kept?'], p: ['Tokenul de autentificare expiră în 7 zile. Preferința de limbă și alegerea cookies rămân până le ștergi tu din browser.', 'Токен входа действует 7 дней. Язык и выбор cookie хранятся, пока вы не очистите их в браузере.', 'Login tokens expire in 7 days. Language and cookie choice stay until you clear them in your browser.'] },
  { h: ['4. Cum le controlezi?', '4. Как управлять?', '4. How to control them?'], p: ['Poți șterge oricând datele site-ului din setările browserului (istoric / date site). Fără stocarea locală, autentificarea nu funcționează, dar rețetele rămân vizibile liber.', 'Данные сайта можно удалить в настройках браузера. Без локального хранилища вход невозможен, но рецепты остаются открытыми.', 'You can delete site data anytime in browser settings. Without local storage login won\'t work, but recipes stay freely visible.'] },
  { h: ['5. Contact', '5. Контакты', '5. Contact'], p: ['Pentru întrebări despre date, scrie-ne din pagina de profil sau prin formularul de contact.', 'Вопросы о данных — через страницу профиля или форму обратной связи.', 'Data questions — reach us from the profile page or the contact form.'] }
];

const FAQ = [
  { q: ['Cum îmi fac cont?', 'Как создать аккаунт?', 'How do I create an account?'], a: ['Apasă Autentificare → Înregistrare, completează numele, emailul și parola, apoi confirmă linkul primit pe email.', 'Нажмите «Вход» → «Регистрация», заполните имя, email и пароль, затем подтвердите ссылку из письма.', 'Click Login → Register, fill in name, email and password, then confirm the link from your email.'] },
  { q: ['Cum votez o rețetă?', 'Как оценить рецепт?', 'How do I rate a recipe?'], a: ['Ai nevoie de cont. Deschide rețeta și alege nota cu stelele din zona de vot.', 'Нужен аккаунт. Откройте рецепт и выберите оценку звёздами.', 'You need an account. Open the recipe and pick stars in the voting area.'] },
  { q: ['Cum devin Autor?', 'Как стать Автором?', 'How do I become an Author?'], a: ['Din Profil → Devino Autor, răspunde la întrebări. Adminul analizează cererea și îți oferă dreptul de publicare.', 'В Профиле → «Стать Автором» ответьте на вопросы. Админ рассмотрит заявку.', 'From Profile → Become an Author, answer the questions. The admin reviews and grants publishing rights.'] },
  { q: ['Cum salvez rețetele preferate?', 'Как сохранять избранное?', 'How do I save favorites?'], a: ['Cu contul logat, apasă inimioara din pagina rețetei. Le găsești în Profil → Favorite.', 'Войдите и нажмите сердечко на странице рецепта. Найдёте их в Профиле → Избранное.', 'Log in and tap the heart on the recipe page. Find them in Profile → Favorites.'] },
  { q: ['Cum îmi șterg contul?', 'Как удалить аккаунт?', 'How do I delete my account?'], a: ['Scrie-ne din pagina de Contact și ștergem contul împreună cu datele asociate.', 'Напишите со страницы контактов — удалим аккаунт и связанные данные.', 'Write to us from the Contact page and we will delete your account and data.'] }
];

module.exports = { GUIDE_ICONS, GUIDE, COOKIES, FAQ };
